### ISSUE TITLE
Slack notification for `trigger = "deploy"` fails

### ISSUE THREAD

**Issue by alinazabara** [rollbar/terraform-provider-rollbar#268]
There is an issue when adding Slack notification for `trigger = "deploy"`.

Here is the TF resource:

```
resource "rollbar_notification" "deploy" {
  rule {
    filters {
      type      = "environment"
      operation = "eq"
      value     = "prod"
    }
    trigger = "deploy"
  }
  channel = "slack"
  config {
    channel = var.slack_channel
  }
}
```

As `show_message_buttons` is defined by default, terraform apply fails with:
```
│ Error: 1 Additional properties are not allowed (u'show_message_buttons' was unexpected)
│
│   with module.ds_prize_preference_notifications.rollbar_notification.deploy_prod,
│   on ../common/modules/rollbar-notifications/notifications_prod.tf line 1, in resource "rollbar_notification" "deploy_prod":
│    1: resource "rollbar_notification" "deploy_prod" {
```

**Comment by dbw0011** [comment]
This may be the intended design, I am not sure but I will find out this week. The deploy message for slack does not have any buttons in the message so it may be documented incorrectly instead of working incorrectly.

Deploy:
![Screen Shot 2022-03-07 at 10 38 10 AM](https://user-images.githubusercontent.com/11859315/157097007-47c98bb6-23ba-429b-b7d2-fe3625c78bad.png)


New item:
![Screen Shot 2022-03-07 at 10 38 21 AM](https://user-images.githubusercontent.com/11859315/157097059-8555f7c5-6c23-483b-95d4-0b106f51b92b.png)

The message buttons are also not present for the "New Version" message so I'll test that as well and make updates to the documentation if that is the case.

**Comment by alinazabara** [comment]
> The deploy message for slack does not have any buttons in the message so it may be documented incorrectly instead of working incorrectly.

The deploy message for slack does not have any buttons indeed. However, `rollbar_notification` terraform resource has `show_message_buttons` defined by default. 

As you can see in my example, I do not have `show_message_buttons` at all in `rollbar_notification`, but the error message still says `'show_message_buttons' was unexpected`.

**Comment by ppsecuk** [comment]
I'm also facing this issue:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/49373111/191758600-f3e5344f-f648-4fb4-a268-4e4cbd0129eb.png">

configuration:
<img width="985" alt="image" src="https://user-images.githubusercontent.com/49373111/191758890-938c5bdf-bcdf-46cf-bd4c-5a1cb2309e88.png">

**Comment by jasonstitt** [comment]
Is there any workaround? I haven't been able to find one as the property has a default value and can't be undefined.

**Comment by rollbar-bborsits** [comment]
Hey @jasonstitt, Are you using the latest Terraform provider? It's version 1.8.0.

**Comment by jasonstitt** [comment]
@rollbar-bborsits yes, v1.8.0

**Comment by rollbar-bborsits** [comment]
@jasonstitt, let us look into this one and find out what goes wrong. I'll get back to you whenever we find out something.

**Comment by rollbar-bborsits** [comment]
@jasonstitt It looks like the provider mishandles some config objects. Unfortunately, the fix is not trivial, so we'll need to figure out how to do that.

**Comment by rollbar-bborsits** [comment]
@jasonstitt, The fix for this issue is estimated to be released by the end of next week.
