### ISSUE TITLE
Bug: Root resource │ was present, but now absent

### ISSUE THREAD

**Issue by stoyanzhekov** [rollbar/terraform-provider-rollbar#359]
This is happening durring `tf apply` from time to time and the 'fix' I use is to make at least one more time `tf apply`

![bug](https://user-images.githubusercontent.com/11327627/228456964-abb75d60-37c0-44d5-909a-46b2e198b369.jpg)

**Comment by rollbar-bborsits** [comment]
Hey @stoyanzhekov, Can you confirm which Terraform version you use?

**Comment by bwmetcalf** [comment]
We are seeing this issue with tf v1.3.6 and rollbar provider 1.12.0.  Applying multiple times does not fix the issue for us.

**Comment by bwmetcalf** [comment]
We were able to work around this by importing the token from rollbar.  The resource created the token, but it seems it doesn't like the response it's getting from the rollbar API.

**Comment by rollbar-bborsits** [comment]
Hey @stoyanzhekov, I'm glad that the workaround solves your issue. Are you sure you're using 1.2.2? We didn't release that version. We released 1.2.0 on 2021-09-10 and 1.3.0 on 2021-09-14. We double-checked if we have a retry logic for all read operations, but everything looks good. Can you collect debug logs if this issue comes up again? This article will tell you how to collect debug logs: https://developer.hashicorp.com/terraform/internals/debugging

**Comment by bwmetcalf** [comment]
This issue continues to be a problem for us.  We are about to upgrade terraform from v1.3.6 to a later version and will report back.  We are using rollbar provider v1.12.0.  The only workaround we've found is to import the rollbar token that gets created into state.

**Comment by rollbar-bborsits** [comment]
Hey @bwmetcalf, Thanks for sharing more details about this case. Configuring the project access token doesn't work, but if you import, it works just fine. Do I understand your workaround correctly?

**Comment by rollbar-bborsits** [comment]
We found the reason behind this issue. We plan to release a fix soon.

**Comment by rollbar-bborsits** [comment]
We released an API fix a few weeks ago that resolves this issue. Feel free to reopen it in case you still bump into it.

**Comment by stefanoaurilio** [comment]
Hey @rollbar-bborsits we ran into the issue again with the rollbar_project_access_token resource.
Here the terraform plan with the detailed logs:

`[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"debug","args":{"name":"stage_post_server_item","scopes":["post_server_item"],"status":"enabled","rate_limit_window_size":60,"rate_limit_window_count":150},"token":{"Name":"stage_post_server_item","project_id":***,"access_token":"***","Scopes":["post_server_item"],"Status":"enabled","rate_limit_window_size":60,"rate_limit_window_count":150,"date_created":1695910994,"date_modified":1695910994,"cur_rate_limit_window_count":0,"cur_rate_limit_window_start":1695910994},"time":"2023-09-28T16:23:14+02:00","message":**"Successfully created new project access token"**}

[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"debug","accessToken":"***","time":"2023-09-28T16:23:14+02:00","message":"Reading resource project access token"}

[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"debug","projectID":636775,"token":"***","time":"2023-09-28T16:23:14+02:00","message":"Reading project access token"}

[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"debug","projectID":636775,"time":"2023-09-28T16:23:14+02:00","message":"Listing project access tokens"}

[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"warn","projectID":636775,"token":"***","time":"2023-09-28T16:23:14+02:00","message":"**Could not find matching project access token**"}

[DEBUG] provider.terraform-provider-rollbar_v1.13.0: {"level":"debug","accessToken":"***","time":"2023-09-28T16:23:14+02:00","message":"Token not found on Rollbar - removed from state"}

[DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot

[ERROR] vertex "rollbar_project_access_token.rollbarProjectToken" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to rollbar_project_access_token.rollbarProjectToken, provider "provider[\"registry.terraform.io/rollbar/rollbar\"]" produced an unexpected
│ new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵`

The token is correctly created but as you can see in the logs but seems is not recognized during the terraform state update. This is impacting us because for every new microservice we create, we also create a corresponding rollbar integration/token and have to manually fix our CI pipelines to complete the terraform apply jobs.

**Comment by rollbar-bborsits** [comment]
Hey, We expected this error to disappear after the API bug fix in August. I’ll talk to the Terraform maintainer about what we can do with this. I’ll keep you updated. I appreciate your debug logs. It will help a lot in finding out what causes the issue.

**Comment by rollbar-bborsits** [comment]
@stefanoaurilio @Giaco9 @Omicron7 I concluded some internal discussions very recently. We completed some database maintenance during the last few weeks that caused a slight replication lag in our databases, which resulted in inconsistent API responses. As Terraform works fast, it's essential to serve the used endpoints accurately. We made some of our endpoints replication lag safe, but some are still affected. I filed a bug ticket to make all endpoints used by Terraform replication lag-safe. I'll make sure to update you when it's out. We plan to make a general fix to this issue in the future, but that requires a more considerable architectural change.

**Comment by rollbar-bborsits** [comment]
We completed the reinforcement of several endpoints, so this issue shouldn't not come up again.

**Comment by aniello-allegretta-ca** [comment]
Hey, i'm a @stefanoaurilio teammate, we're experiencing this error again. We'are still using the v1.13.0 provider version and the error is exactly the same.

[ERROR] vertex "rollbar_project_access_token.rollbarProjectToken" error: Provider produced inconsistent result after apply
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to rollbar_project_access_token.rollbarProjectToken, provider "provider["registry.terraform.io/rollbar/rollbar"]" produced an unexpected
│ new value: Root resource was present, but now absent.

Therefore, we tried updating the provider version with the latest (v1.16.0), after that we started receving this error:

| Something went wrong: Exited code received 1: rollbar_project_access_token.rMicroServiceGOBRollbarToken: Creating...  Error: 1 LEGACY token is not enabled

Could you help?
