### ISSUE TITLE
Support better management of Project's sub-features/settings

### ISSUE THREAD

**Issue by JamieSinn** [rollbar/terraform-provider-rollbar#375]
Currently we can manage the creation of projects, but we can't control or manage the sub-features within a project.

Specifically the following would be really helpful to be able to manage as resources and data records:
- Time Zone
- Time Format
- Environments
- Source Control
- IP Blocklist
- Expired Tokens (as this is a new feature - it would be a good data record for a project)

Currently we can't really fully utilize terraform to standardize or automate creation or management of the projects.

**Comment by rollbar-bborsits** [comment]
Hey @JamieSinn, Thanks for your feature request. We're working on some updates. Let me share where we're.

> Time Zone
> Time Format

We're working on this actively now. It's expected to be out in October.

> Environments

This is a tough one, unfortunately. Whenever Rollbar finds a new environment in an occurrence, it adds it to the DB automatically. This goes against the way Terraform works, as it has complete control over what object was created, modified, or deleted. Because of this mismatch, we're unable to implement environment-related Terraform features. Environment handling is a good candidate for the API tho, so I'll file a feature request.

> Source Control
> IP Blocklist
> Expired Tokens

Can you elaborate on the specific use cases? What exact actions do you want to configure on the resources above? We don't have Public API endpoints for those, so we will need to create them. We want to design the endpoints to fit the use cases accordingly, hence my questions.

**Comment by JamieSinn** [comment]
Thanks for the reply! 
Happy to elaborate a bit more:

## Source Control:
We want to be able to bind our monorepo to all the services as needed via terraform - to prevent needing to log into the service account and manually connect each repo each time. This is more of an automation aspect than a pure "terraform" esque solution.

## IP Blocklist:
Same as above - we have a general list of IPs that we block from accessing our networks for security - and same as above - copy pasting from Terraform to Rollbar every time would be quite tedious. This use case was compounded with the recent Rollbar breach.

## Expired Tokens:
- This would be a data resource - so that we can pull in and ensure that they're not being used/referenced anywhere in our secrets management/source.

**Comment by rollbar-bborsits** [comment]
@JamieSinn Thanks for detailing your use cases. I created an internal ticket on our Idea board, so I'll close this ticket for now. Feel free to reopen it in case you want to share more info.
